<?php

namespace EventAndAnnonceBundle\Repository;

/**
 * AnnonceFavorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceFavorisRepository extends \Doctrine\ORM\EntityRepository
{

    public function deleteLike($cin,$idA){
        $query=$this->getEntityManager()->createQuery('DELETE EventAndAnnonceBundle:AnnonceFavoris a WHERE a.cin = :cin AND a.idA= :idA')
            ->setParameter('cin',$cin)->setParameter('idA',$idA);
        $query->execute();
    }

    public function readFavoris($cin){
        $query=$this->getEntityManager()->createQuery('SELECT a FROM EventAndAnnonceBundle:Annonce a WHERE a.idAnnonce IN (SELECT f.idA FROM EventAndAnnonceBundle:AnnonceFavoris f WHERE f.cin = :cin)')
            ->setParameter('cin',$cin);
       return $query->getResult();
    }

    /*public function readFavoris($cin){
        $query=$this->getEntityManager()->createQuery('SELECT a FROM ZanimauxBundle:Annonce a ');

        $query->getResult();
    }*/
}
