<?php

namespace EventAndAnnonceBundle\Repository;

/**
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends \Doctrine\ORM\EntityRepository

{


    public function deleteParticipants($cin,$idEvt){
        $query=$this->getEntityManager()->createQuery('DELETE EventAndAnnonceBundle:Participation p WHERE p.cin = :cin AND p.idEvt= :idEvt')
            ->setParameter('cin',$cin)->setParameter('idEvt',$idEvt);
        $query->execute();
    }



    public function exist($user,$idEvt){
        $query= $this->createQueryBuilder('p')
            ->where('p.cin =:user')->andWhere('p.idEvt=:idEvt')
            ->setParameter('user',$user.'%')
            ->setParameter('idEvt', $idEvt.'%')
            ->getQuery();

        return $query->getResult();

    }

}
