<?php

namespace ZanimauxBundle\Repository;

/**
 * QuestionnaireChienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionnaireChienRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRaceChien($tolererChien,$tolererChat,$affectueux,$calme,$intelligent,$chutePoils){

        $query=$this->getEntityManager()
            ->createQuery("
                      select p from RefugeBundle:QuestionnaireChien p WHERE p.tolererChien=:tolererChien AND p.tolererChat=:tolererChat
                      AND p.affectueux=:affectueux AND p.calme=:calme  AND p.intelligent=:intelligent AND p.chutePoils=:chutePoils
                      ")
            ->setParameter('tolererChien',$tolererChien)
            ->setParameter('tolererChat',$tolererChat)


            ->setParameter('affectueux',$affectueux)
            ->setParameter('calme',$calme)
            ->setParameter('intelligent',$intelligent)
            ->setParameter('chutePoils',$chutePoils)
        ;
        return $query->getResult();
    }
}
