<?php

namespace RefugeBundle\Repository;

/**
 * QuestionnaireChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionnaireChatRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRaceChat($tolererChien,$dynamique,$affectueux,$chutePoils,$intelligent,$acceptationEtranger){

        $query=$this->getEntityManager()
            ->createQuery("
                      select p from RefugeBundle:QuestionnaireChat p WHERE p.tolererChien=:tolererChien AND p.dynamique=:dynamique
                      AND p.affectueux=:affectueux AND p.chutePoils=:chutePoils AND p.intelligent=:intelligent AND p.acceptationEtranger=:acceptationEtranger
                      ")
            ->setParameter('tolererChien',$tolererChien)
            ->setParameter('dynamique',$dynamique)
            ->setParameter('affectueux',$affectueux)
            ->setParameter('chutePoils',$chutePoils)
            ->setParameter('intelligent',$intelligent)
            ->setParameter('acceptationEtranger',$acceptationEtranger)
        ;
        return $query->getResult();
    }

    public function findChat($tolererChien,$dynamique,$affectueux,$chutePoils,$intelligent,$acceptationEtranger)
    {
        $q = $this->getEntityManager()
            ->createQuery("SELECT m from RefugeBundle:Race m
                               WHERE m.id IN 
                               (SELECT p.race from RefugeBundle:QuestionnaireChat p 
                                WHERE p.tolererChien=:tolererChien AND p.dynamique=:dynamique
                      AND p.affectueux=:affectueux AND p.chutePoils=:chutePoils AND p.intelligent=:intelligent AND p.acceptationEtranger=:acceptationEtranger
                      ")->setParameter('tolererChien',$tolererChien)
            ->setParameter('dynamique',$dynamique)
            ->setParameter('affectueux',$affectueux)
            ->setParameter('chutePoils',$chutePoils)
            ->setParameter('intelligent',$intelligent)
            ->setParameter('acceptationEtranger',$acceptationEtranger);
        return $q->getResult();

    }
}
