<?php

namespace MagasinBundle\Repository;

/**
 * produitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produitRepository extends \Doctrine\ORM\EntityRepository
{

    public function findProduit($idMagasin){

        $query=$this->getEntityManager()
            ->createQuery("
                      select p from MagasinBundle:Produit p WHERE p.idMagasin =:idMagasin
                      ")
            ->setParameter('idMagasin',$idMagasin);
        return $query->getResult();
    }

    public function findIdMagasin($idProp)
    {

        $q = $this->getEntityManager()
            ->createQuery("SELECT p from MagasinBundle:Produit p
                               WHERE p.idMagasin IN 
                               (SELECT m.idMagasin from MagasinBundle:Magasin m 
                                WHERE m.cinProprietaireMagasin=:idProp)")->setParameter('idProp',$idProp);
        return $q->getResult();

    }
// get le produit ayant un id $idProduit
    public function selectIdMagasin($idProduit)
    {
        $q=$this->getEntityManager()
            ->createQuery(" select p from MagasinBundle:Produit p 
                                WHERE p.idProduit =:idProduit")
        ->setParameter('idProduit',$idProduit);
        return $q->getSingleResult() ;
    }

}