<?php

namespace PetSitterDresseurBundle\Repository;

/**
 * ParcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcRepository extends \Doctrine\ORM\EntityRepository
{
    public function findParcDQL($nom){
        $q= $this->getEntityManager()
            ->createQuery("SELECT p FROM PetSitterDresseurBundle:Parc p WHERE p.nomParc LIKE :nom
                                OR p.CategorieDressage LIKE :nom 
                                OR p.adresseParc LIKE :nom
                                 ")
            ->setParameter('nom','%'.$nom.'%');
        return $q->getResult();
    }


}
