<?php

namespace PetSitterDresseurBundle\Repository;

/**
 * PromenadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromenadeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPromenadeDQL($nom){
        $q= $this->getEntityManager()
            ->createQuery("SELECT p FROM PetSitterDresseurBundle:Promenade p WHERE p.nomPromenade LIKE :nom
                                OR p.typePromenade LIKE :nom 
                                OR p.lieuPromenade LIKE :nom
                                 ")
            ->setParameter('nom','%'.$nom.'%');
        return $q->getResult();
    }
}
