<?php

namespace PetSitterDresseurBundle\Repository;



/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function count1DQL($roles){
        $qb=$this->getEntityManager()
            ->createQuery("select count (u) as nb 
                            from ZanimauxBundle:USER u 
                            WHERE u.roles LIKE :n")
        ->setParameter('n',$roles);
        return $qb->getResult();
    }
}
