<?php

namespace VeterinaireBundle\Repository;
use VeterinaireBundle\Entity\Article;


/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

    public function RechercheArticle($cin){
        $q= $this->getEntityManager()
            ->createQuery("select c from VeterinaireBundle:Article c
            WHERE c.cin=:cin")->setParameter('cin',$cin);

        return $q->getResult();


    }

}
