<?php

namespace VeterinaireBundle\Repository;
use VeterinaireBundle\Entity\Cabinet;


/**
 * CabinetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CabinetRepository extends \Doctrine\ORM\EntityRepository
{

    public function RechercheCabinet($cin){
        $q= $this->getEntityManager()
            ->createQuery("select c from VeterinaireBundle:Cabinet c
            WHERE c.cin=:cin")->setParameter('cin',$cin);

        return $q->getResult();


    }

}
