<?php

namespace VeterinaireBundle\Repository;
use VeterinaireBundle\Entity\Calendrier;

/**
 * CalendrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendrierRepository extends \Doctrine\ORM\EntityRepository
{

    public function FindByVet($cin){
    $q= $this->getEntityManager()
        ->createQuery("select c from VeterinaireBundle:Calendrier c
            WHERE c.cin=:cin")->setParameter('cin',$cin);

    return $q->getResult();


}
}
