<?php

namespace VeterinaireBundle\Repository;

/**
 * RendezvsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RendezvsRepository extends \Doctrine\ORM\EntityRepository
{
}
